// <auto-generated />
using BusinessLogic.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace BusinessLogic.Contexts.Migrations
{
    [DbContext(typeof(WhitelistContext))]
    [Migration("20180503170857_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BusinessLogic.Contexts.Entities.Adres", b =>
                {
                    b.Property<string>("Postcode")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Postcode");

                    b.ToTable("Adressen");
                });

            modelBuilder.Entity("BusinessLogic.Contexts.Entities.Bsn", b =>
                {
                    b.Property<int>("Bsnnummer");

                    b.HasKey("Bsnnummer");

                    b.ToTable("Bsns");
                });

            modelBuilder.Entity("BusinessLogic.Contexts.Entities.BsnUzovi", b =>
                {
                    b.Property<int>("Bsnnummer");

                    b.Property<short>("Uzovi");

                    b.HasKey("Bsnnummer", "Uzovi");

                    b.ToTable("BsnUzovis");
                });
#pragma warning restore 612, 618
        }
    }
}
