

















// <auto-generated />
#pragma warning disable 1591
namespace Services.Wcf
{
    using System.ServiceModel;

    using Contracts;


    [ServiceContract(Namespace = "https://github.com/k7o/SOLID/queryservice/v1.0")]
    public class NonDotNetQueryService
    {

		private static TResult Execute<TResult>(IQuery<TResult> query) => (TResult)QueryService.ExecuteQuery(query);
	}
}
